version: "3.7"
services:
  mongodb:
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
  ms-config-server:
    container_name: ms-config-server
    build:
      context: ../ms-config-server/ms-config-server
    ports:
      - 8888:8888
  ms-discovery:
    container_name: ms-discovery
    build:
      context: ../ms-discovery
    ports:
      - 9093:9093
    depends_on:
      - ms-config-server
  ms-gateway:
    container_name: ms-gateway
    build:
      context: ../ms-gateway
    ports:
      - 9090:9090
    depends_on:
      - ms-discovery
      - ms-config-server
  ms-client:
    container_name: ms-client
    build:
      context: ../ms-client
    ports:
      - 8080:8080
    links:
      - mongodb
    depends_on:
      - mongodb
      - ms-config-server
      - ms-discovery
  ms-bank-account:
    container_name: ms-bank-account
    build:
      context: ../ms-bank-account
    ports:
      - 8085:8085
    links:
      - mongodb
    depends_on:
      - mongodb
      - ms-config-server
      - ms-discovery
  ms-credits:
    container_name: ms-credits
    build:
      context: ../ms-credits
    ports:
      - 8084:8084
    links:
      - mongodb
    depends_on:
      - mongodb
      - ms-config-server
      - ms-discovery
  ms-loan:
    container_name: ms-loan
    build:
      context: ../ms-loan
    ports:
      - 8081:8081
    links:
      - mongodb
    depends_on:
      - mongodb
      - ms-config-server
      - ms-discovery
  ms-movement:
    container_name: ms-movement
    build:
      context: ../ms-movement
    ports:
      - 8083:8083
    links:
      - mongodb
    depends_on:
      - mongodb
      - ms-config-server
      - ms-discovery